### PR TITLE
Switch to using the Vary: X-Inertia header

### PR DESCRIPTION
**Pull request by swarakaka**
According to changes in inertia-laravel version 0.6.4
[#404](https://github.com/inertiajs/inertia-laravel/commit/d00512eb3faa5dfc3a432e0778866f34fe5eff62)

### CODE REVIEW

**Review by BrandonShar — APPROVED** [review]
Thanks!

**Comment by BrandonShar** [comment]
I'm a little slow to cut releases right now because it's American Thanksgiving week so I appreciate your patience! I'll get this in a new release early next week!

**Comment by pauldiepold** [comment]
Actually this breaks my django-inertia application. Inertia (Vue 3) doesn't recognize the responses:
`All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.`
Is there any quick fix?

**Comment by BrandonShar** [comment]
Oops, sorry about that @pauldiepold ! Are you able to update your inertia js libraries? If not I’ll push a hot fix today

**Comment by pauldiepold** [comment]
@BrandonShar Thanks for your fast reply! I To which version should i update? I'm currently on Inertia 0.11.1 and inertia-vue 0.6.0, i though those are the newest?

**Comment by swarakaka** [comment]
Hello @pauldiepold 
can you change the bellows code in your local:
**inertia-django/inertia/http.py**
`headers={
        'X-Inertia': True,
      },`

**Comment by BrandonShar** [comment]
Looks like I missed a similar error in react. I'm going to revert this while we figure out what's going on. Thanks for reporting @pauldiepold !

**Comment by BrandonShar** [comment]
Just tagged `0.5.1` and confirmed the fix. @swarakaka let's figure out if Inertia Laravel either didn't tag the release you mentioned or maybe they're modifying the header somewhere else?

**Comment by swarakaka** [comment]
The inertia-laravel modified the header [here](https://github.com/inertiajs/inertia-laravel/blob/b00fe8cf741766b41de69978f9e90ee6d1470d36/src/Response.php#L107)

**Comment by pauldiepold** [comment]
Thanks for the quick fix!

Actually i think that the modification in inertia-laravel is only meant for internal usage. Not in the base inertia package nor any of the frontend adapters were made any changes, so inertia still expects the response to contain the `'X-Inertia': True` header. So the revert should be correct :)

**Pull request merged**
